import {esc,arrow,button,nav,footer} from './ui.mjs';
import {editorial} from './pages.mjs';
const richImage = image => `<figure class="case-media"><a href="../assets/${esc(image.src)}" target="_blank" rel="noopener noreferrer"><img src="../assets/${esc(image.src)}" alt="${esc(image.alt)}" loading="lazy" decoding="async"></a><figcaption>${esc(image.caption||'')}</figcaption></figure>`;
const blocks = values => (values||[]).map(b=>{
 if(typeof b==='string')return `<p>${esc(b)}</p>`;
 if(b.heading)return `<h3>${esc(b.heading)}</h3>`;
 if(b.list)return `<ul>${b.list.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>`;
 if(b.type==='image')return richImage(b);
 if(b.type==='video')return `<figure class="case-media video-media"><video controls playsinline preload="none"${b.poster?` poster="../assets/${esc(b.poster)}"`:''} aria-label="${esc(b.alt)}"><source src="../assets/${esc(b.src)}" type="video/mp4"></video><figcaption>${esc(b.caption)}</figcaption></figure>`;
 if(b.type==='comparison')return `<div class="comparison" role="group" aria-label="Design iteration comparison">${['before','after'].map(side=>`<div><p class="eyebrow">${esc(b[side].label)}</p>${richImage(b[side])}</div>`).join('')}</div>`;
 if(b.type==='journey')return `<div class="journey"><p class="eyebrow">${esc(b.label)}</p><ol>${b.steps.map((step,i)=>`<li><span class="eyebrow">0${i+1}</span><strong>${esc(step.title)}</strong><p>${esc(step.detail)}</p></li>`).join('')}</ol></div>`;
 if(b.type==='relatedWork')return `<a class="related-work" href="../${esc(b.slug)}/"><span class="eyebrow">${esc(b.eyebrow)}</span><strong>${esc(b.title)} ${arrow}</strong><p>${esc(b.text)}</p></a>`;
 return '';
}).join('');
export function caseStudy(project,p,next){
 const e=editorial[project.slug];
 const media=(file,label)=>file.endsWith('.mp4')?`<figure class="case-media video-media"><video controls playsinline preload="none" poster="../assets/optimized/${esc(file.replace('.mp4','-poster.jpg'))}" aria-label="${esc(p.title+' — '+label)}"><source src="../assets/${esc(file)}" type="video/mp4">Your browser does not support video. <a href="../assets/${esc(file)}">Download demonstration</a></video><figcaption>${esc(label)} · Interface demonstration</figcaption></figure>`:`<figure class="case-media reveal"><a href="../assets/${esc(file)}" target="_blank" rel="noopener noreferrer" aria-label="Open ${esc(label)} at full size"><img src="../assets/${file.endsWith('.gif')?'optimized/wao-usability-still.jpg':esc(file)}" alt="${esc(p.title+' — '+label)}" loading="lazy" decoding="async"></a><figcaption><span>${esc(label)}</span><span aria-hidden="true">${file.endsWith('.gif')?'Open animation':'Expand'} ↗</span></figcaption></figure>`;
 const section=(s,i)=>`<section class="case-section ${p.chapterNavigation?'case-section--chapter':''} ${s.blocks?.some(b=>b.type)?'case-section--rich':''}" id="${esc(s.id||`section-${i}`)}"><div class="section-label"><p class="eyebrow">${String(i+1).padStart(2,'0')} / ${esc(s.date||'Design study')}</p><h2>${esc(s.title)}</h2></div><div class="section-body prose">${blocks(s.blocks)}</div>${(s.media||[]).map((m,j)=>media(m,p.mediaLabels?.[m]||`${s.title}${s.media.length>1?' / '+String(j+1).padStart(2,'0'):''}`)).join('')}</section>`;
 let chapters;
 if(p.chapterNavigation) chapters=p.sections.map((s,i)=>({id:'chapter-'+s.id,name:(s.chapterLabel||s.title).replace(/^\d+\s*·\s*/, ''),intro:s.title,indexes:[i]}));
 else if(project.slug==='fohlio') chapters=[{id:'context',name:'Context',intro:'The bigger picture.',indexes:[0,1]},{id:'orient',name:'Orient',intro:'A clearer way through.',indexes:[2,3]},{id:'discover',name:'Discover',intro:'From searching to finding.',indexes:[4,5,6]},{id:'scale',name:'Scale',intro:'Built to work together.',indexes:[7,8,9]},{id:'outcomes',name:'Outcomes',intro:'What the work changed.',indexes:[10]}];
 else {const final=p.sections.findIndex(s=>/Accessibility|Next Steps/.test(s.title));chapters=[{id:'context',name:'Context',intro:'Understanding the problem.',indexes:p.sections.map((_,i)=>i).filter(i=>i<2)},{id:'decisions',name:'Decisions',intro:'Turning insights into interactions.',indexes:p.sections.map((_,i)=>i).filter(i=>i>=2&&(final<0||i<final))},{id:'outcomes',name:'Reflection',intro:'Looking beyond the screen.',indexes:p.sections.map((_,i)=>i).filter(i=>final>=0&&i>=final)}].filter(c=>c.indexes.length);}
 const chapterHTML=chapters.map((c,n)=>{const demoIndexes=c.indexes.filter(i=>p.sections[i].media?.some(m=>m.endsWith('.mp4')));let demosRendered=false;return `<section class="chapter" id="${c.id}"><div class="chapter-heading"><span class="eyebrow">CHAPTER ${String(n+1).padStart(2,'0')}</span><h2>${c.intro}</h2></div>${c.indexes.map(i=>{if(demoIndexes.length>1&&demoIndexes.includes(i)){if(demosRendered)return '';demosRendered=true;return `<div class="demo-gallery" data-demo-gallery><div class="demo-tabs" role="tablist" aria-label="${esc(p.title)} demonstrations" hidden>${demoIndexes.map((di,j)=>`<button type="button" role="tab" id="demo-tab-${di}" aria-controls="demo-panel-${di}" aria-selected="${j===0}" tabindex="${j===0?0:-1}">${esc(p.sections[di].title)}</button>`).join('')}</div>${demoIndexes.map(di=>`<div class="demo-panel" id="demo-panel-${di}" data-demo-panel>${section(p.sections[di],di)}</div>`).join('')}</div>`;}return section(p.sections[i],i);}).join('')}</section>`;}).join('');
 const decisionStory=project.slug==='fohlio'?`<section class="decision-story wrap" aria-label="Three decisions behind the redesign" data-decision-story><div class="decision-stage" aria-hidden="true" hidden>${[3,4,8].map((i,j)=>`<img src="../assets/${p.sections[i].media[0]}" alt="" loading="lazy" data-decision-image="${j}">`).join('')}<span class="decision-counter eyebrow">DESIGN DECISIONS / <span data-decision-counter>01</span> — 03</span></div><div class="decision-steps">${[
 ['01','Keep people oriented.','A consistent navigation framework reduces context-switching, with breadcrumbs and quick access that keep the next step in reach.',3,'orient'],
 ['02','Bring the details closer.','A flexible side sheet puts product information beside the library, so people can evaluate an item without losing their place.',4,'discover'],
 ['03','Make the everyday clearer.','Shared table patterns bring readable type, better spacing, and consistent editing to the platform’s most-used component.',8,'scale']
 ].map(([n,title,copy,i,chapter],j)=>`<article class="decision-step" data-decision-step="${j}"><p class="eyebrow">${n} / Inside the redesign</p><h2>${title}</h2><p>${copy}</p><a class="text-link" href="#${chapter}">Explore this decision ${arrow}</a><img class="decision-fallback" src="../assets/${p.sections[i].media[0]}" alt="${esc(title)} Fohlio interface detail" loading="lazy"></article>`).join('')}</div></section>`:'';
 const proof=project.slug==='fohlio'?`<div class="evidence-strip"><div><span class="eyebrow">Reported by project managers</span><strong>40% <span>faster decisions</span></strong></div><div><span class="eyebrow">Early workflow testing</span><strong>35% <span>fewer clicks</span></strong></div><p class="detail">Results describe individual redesign areas. Goals and projected improvements are identified within the study.</p></div>`:'';
 return `${nav('../')}<main id="main"><section class="case-hero wrap"><a class="case-back detail" href="../#portfolio">← Selected work</a><div class="case-headline"><div><p class="eyebrow">${esc(p.eyebrow||e.label)}</p><h1>${esc(p.title.toUpperCase())}<span>${p.headline?esc(p.headline):e.headline.replaceAll('<br>',' ')}</span></h1></div><p>${e.summary}</p></div><div class="case-hero-stage ${p.fullWidthHero?'case-hero-stage--wide':''}" style="--stage:${e.color||'#e4e5dc'};view-transition-name:project-${project.slug}">${p.hero.map((m,i)=>`<img src="../assets/${esc(m)}" alt="${esc(p.heroLabels?.[i]||p.title+' product interface'+(p.hero.length>1?' '+(i+1):''))}" fetchpriority="${i===0?'high':'auto'}" decoding="async">`).join('')}<span class="eyebrow">${esc(e.note)} / ${esc(p.duration)}</span></div><div class="case-summary"><div><p class="eyebrow">The short version</p><p class="summary-lead">${esc(p.problem)}</p></div><dl><div><dt>Contribution</dt><dd>${esc(p.contribution)}</dd></div><div><dt>Duration</dt><dd>${esc(p.duration)}</dd></div>${p.status?`<div><dt>Status</dt><dd>${esc(p.status)}</dd></div>`:''}${p.collaborators?`<div><dt>Collaborated with</dt><dd>${esc(p.collaborators)}</dd></div>`:''}</dl></div>${proof}<div class="case-actions">${button('Read the story','#'+chapters[0].id)}${button('Jump to '+(project.slug==='fohlio'?'outcomes':'reflection'),'#'+chapters.at(-1).id)}</div></section>${decisionStory}<div class="case-layout wrap"><aside class="chapter-nav"><span class="eyebrow">In this study</span><nav aria-label="Case study chapters">${chapters.map((c,i)=>`<a href="#${c.id}" data-chapter-link><span>0${i+1}</span>${c.name}</a>`).join('')}</nav><a href="#contact" class="chapter-contact detail">Let’s talk ${arrow}</a></aside><div class="case-content"><div class="case-context prose"><p>${esc(p.overview)}</p>${blocks(p.role)}</div>${(p.overviewMedia||[]).map((m,i)=>media(m,p.mediaLabels?.[m]||`${p.title} / Product overview ${i+1}`)).join('')}${chapterHTML}<a class="next-project" href="../${next.slug}/"><span class="eyebrow">Keep exploring / Next project</span><strong>${esc(next.title)}</strong>${arrow}</a></div></div></main>${footer('../')}`;
}
