export const esc = s => String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export const arrow = '<span class="arrow" aria-hidden="true">↗</span>';
export const button = (label,href,solid=false) => `<a class="button${solid?' button--solid':''}" href="${esc(href)}">${esc(label)}${arrow}</a>`;
export const nav = (base,active='work') => `<header class="site-header"><div class="nav-wrap wrap"><a href="${base}" class="brand" aria-label="Nicolas Sanabria — home"><img src="${base}assets/logo.svg" width="70" height="47" alt=""></a><a class="nav-identity detail" href="${base}">Nicolas Sanabria<span>Product designer · NYC</span></a><nav aria-label="Main navigation"><a href="${base}#portfolio" ${active==='work'?'aria-current="page"':''}>Work<span class="nav-dot" aria-hidden="true"></span></a><a href="${base}About/" ${active==='about'?'aria-current="page"':''}>About<span class="nav-dot" aria-hidden="true"></span></a><a href="#contact">Let’s talk ${arrow}</a></nav></div></header>`;
export const footer = base => `<footer id="contact" class="site-footer"><div class="wrap"><div class="footer-top detail"><span>GOOD WORK STARTS WITH A CONVERSATION.</span><span>New York, NY ↗</span></div><a class="contact-title" href="mailto:nicksanota@gmail.com">LET’S MAKE<br>SOMETHING <span>MATTER.</span>${arrow}</a><div class="footer-bottom"><div class="email-row"><a href="mailto:nicksanota@gmail.com">nicksanota@gmail.com</a><button class="copy-button" type="button" data-copy-email aria-label="Copy email address">Copy ↗</button><span class="copy-status sr-only" role="status" aria-live="polite"></span></div><a class="detail" href="https://www.linkedin.com/in/ncksanota/" target="_blank" rel="noopener noreferrer">LinkedIn ${arrow}</a></div><div class="footer-colophon detail"><span>© ${new Date().getFullYear()} Nicolas Sanabria</span><button class="motion-toggle" type="button" data-motion-toggle aria-label="Enable decorative motion" aria-pressed="true" hidden>Motion on</button><a href="#main">Back to top ↑</a></div></div></footer>`;
export function shell({title,description,body,base='./',pathname='',siteURL,theme='light',socialImage:customSocialImage}) {
 const pageURL=pathname===null?null:new URL(pathname,siteURL).href;
 const socialImage=new URL('assets/'+(customSocialImage||'Se27uSPfxrflC01YaaGHXVaMms.png'),siteURL).href;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#edff50"><title>${esc(title)} — Nicolas Sanabria</title><meta name="description" content="${esc(description)}">${pageURL?`<link rel="canonical" href="${esc(pageURL)}"><meta property="og:url" content="${esc(pageURL)}">`:''}<meta property="og:type" content="website"><meta property="og:site_name" content="Nicolas Sanabria"><meta property="og:title" content="${esc(title)} — Nicolas Sanabria"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="${esc(socialImage)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)} — Nicolas Sanabria"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${esc(socialImage)}"><link rel="icon" href="${base}assets/FcKGaeV308Gr1frry5QgNy0JUe8.svg" type="image/svg+xml"><link rel="preload" href="${base}assets/1Ptgg87LROyAm3Kz-C8.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="${base}fonts.css"><link rel="stylesheet" href="${base}styles/tokens.css"><link rel="stylesheet" href="${base}styles/primitives.css"><link rel="stylesheet" href="${base}style.css"><script src="${base}site.js" defer></script></head><body data-theme="${theme}"><a class="skip-link" href="#main">Skip to content</a>${body}</body></html>`;
}
